name: VC Investment Radar

on:
  schedule:
    - cron: '5 0 * * *'   # 毎日 09:05 JST
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # どの階層に置いたか自動検出して env.ROOT に保存
      - name: Detect project root
        run: |
          echo "== repo tree =="
          ls -la
          ROOT="."
          if [ -f requirements.txt ] && [ -d scripts ]; then
            ROOT="."
          elif [ -f vc_investment_radar_site/requirements.txt ]; then
            ROOT="vc_investment_radar_site"
          elif [ -f vc_investment_radar/requirements.txt ]; then
            ROOT="vc_investment_radar"
          else
            echo "requirements.txt が見つからない。ファイルの階層を確認してください。" >&2
            exit 1
          fi
          echo "ROOT=$ROOT" >> $GITHUB_ENV
          echo "Detected ROOT=$ROOT"

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles(format('{0}/requirements.txt', env.ROOT)) }}

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ${{ env.ROOT }}

      - name: Run fetch
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          python scripts/fetch.py
        working-directory: ${{ env.ROOT }}

      - name: Commit outputs (output/, data/, docs/)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git pull --rebase || true
          git add ${{ env.ROOT }}/output/ ${{ env.ROOT }}/data/ ${{ env.ROOT }}/docs/ || true
          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "chore: update feed & digest"
            git push
          fi
